version: "3.7"

services:

  postgres:
    container_name: postgres
    image: "postgres:12.0"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: postgres
